### ISSUE TITLE
Create Spec Helper Modules

### ISSUE THREAD

**Issue by wkirby** [apsislabs/slayer#11]

**Comment by ncallaway** [comment]
Unless you have a specific plan for what we want to do with spec helper modules, I'd recommend we hold off and start implementing this into a project or two before we decide what helper modules we'd like to have.

**Comment by wkirby** [comment]
Cool.

**Comment by ncallaway** [comment]
First helpers desired:

assert_success Invites::InviteUserCommand.call(@invite_user_form, @inviter)
assert_failure Invites::InviteUserCommand.call(@invite_user_form, @inviter)

**Comment by ncallaway** [comment]
assert_success and assert_failure should also have the ability to optionally specify a status that they will validate also.

```
assert result.failure?
 assert_equal :redeemed, result.status
```

**Comment by Crisfole** [comment]
This is complete. The matchers themselves are tested.
