### ISSUE TITLE
Provide Rails Extension Methods for Command

### ISSUE THREAD

**Issue by ncallaway** [apsislabs/slayer#22]
When in Rails we should provide similar syntactic sugar on a Command that Rectify does.

Example: the transition method in Rectify Command (see: https://github.com/andypike/rectify/blob/master/lib/rectify/command.rb) should be available when the rails extension method for Slayer has been loaded.

**Comment by wkirby** [comment]
Moved to [apsislabs/slayer_rails](https://github.com/apsislabs/slayer_rails)
